name: Deploy
on:
  pull_request:
  release:
    types:
      - published

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build JS dependencies
        uses: PrestaShopCorp/github-action-build-js/12@v1.0
        with:
          cmd: yarn
          path: ./_dev
      - name: Install composer dependencies
        run: composer install --no-dev -o
      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0
      - name: Create & upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ps_checkout
          path: ../
      - name: Publish to GitHub Release
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          $latest_release = (Invoke-WebRequest https://api.github.com/repos/${{ github.repository }}/releases | ConvertFrom-Json).Get(0)
          $major, $minor = $latest_release.tag_name.replace('v','').split('.')
          Set-Content -Path .\configs\majorVersion.hpp -Value $major -Force -NoNewline
          Set-Content -Path .\configs\minorVersion.hpp -Value $minor -Force -NoNewline
          $uploadurl = $latest_release.upload_url
          $changelog = $latest_release.body
          Set-Content -Path .\_uploadurl -Value $uploadurl -Force -NoNewline
          Set-Content -Path .\_changelog -Value $changelog -Force -NoNewline
          echo $uploadurl
