name: JS tests
on: [push, pull_request]
jobs:
  js-linter:
    name: JS linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn --cwd _dev/ install
      - run: yarn --cwd _dev/ lint
      - name: build
        uses: PrestaShopCorp/github-action-build-js/12.14.1@dev
        with:
          cmd: yarn
          path: ./_dev
      - name: clean dependencies
        uses: PoulainMaxime/github-action-clean-before-deploy@master
      - name: deploy artifact
        uses: actions/upload-artifact@v1
        with:
          name: ps_checkout
          path: .
